variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LANG: en_US.UTF-8

stages:
  - build
  - release

build:
  tags:
    - docker
  stage: build
  image: crops/yocto:debian-9-base
  script:
    - . ./setup-env -m ifc1410-64b
    - bitbake ess-image
  artifacts:
    paths:
      - tmp/deploy/images/ifc1410-64b
    expire_in: 12 hour

release:
  tags:
    - docker
  stage: release
  image: registry.esss.lu.se/ics-docker/jfrog:latest
  script:
    - jfrog rt config artifactory --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY}
    - cd sstate-cache && jfrog rt upload --flat=false "*" yocto/sstate/
